# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercici',
            name='tema',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
