# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160517_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='resposta_User',
        ),
        migrations.AddField(
            model_name='resposta_user',
            name='usuari',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='application.Perfil'),
            preserve_default=False,
        ),
    ]
