# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20160517_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta_user',
            name='exercici',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='application.Exercici'),
            preserve_default=False,
        ),
    ]
