# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20160517_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercici',
            name='comentari_professor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
