# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20160518_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercici',
            name='comentari_professor',
        ),
        migrations.AddField(
            model_name='resposta_user',
            name='comentari_professor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
