# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20160519_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='nivell',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Curs'),
        ),
    ]
