# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20160520_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercici',
            name='enunciat',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resposta_possible',
            name='resposta',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resposta_user',
            name='resposta',
            field=models.TextField(max_length=500),
        ),
    ]
