# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20160521_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta_user',
            name='comentari_professor',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
