# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20160522_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta_possible',
            name='exercici',
        ),
        migrations.AddField(
            model_name='exercici',
            name='nom',
            field=models.CharField(default='Les sodes de la senyora', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resposta_possible',
        ),
    ]
